#!/usr/bin/env bash
# Register the host generated by Copier through Maison's validated host:add task.
set -euo pipefail

error() {
  printf 'error: overlay host setup: %s\n' "$*" >&2
  exit 1
}

maison_home="${MAISON_HOME:-}"
overlay_path="${MAISON_OVERLAY_PATH:-$(pwd -P)}"
host="${MAISON_HOST:-$(hostname -s)}"
username="${USERNAME:-}"

[ -n "$maison_home" ] || error 'MAISON_HOME must point to a Maison checkout; rerun Copier from Maison'
[ -d "$maison_home" ] || error "Maison checkout does not exist: $maison_home"
[ -n "$username" ] || error 'Copier did not provide the inventory username'
command -v git >/dev/null 2>&1 || error 'git is required to initialize the overlay repository'
command -v mise >/dev/null 2>&1 || error 'mise is required to register the current host'

case "$(uname -s):$(uname -m)" in
  Darwin:arm64 | Darwin:aarch64) system=aarch64-darwin ;;
  Linux:arm64 | Linux:aarch64) system=aarch64-linux ;;
  Linux:x86_64 | Linux:amd64) system=x86_64-linux ;;
  *) error "unsupported platform $(uname -s)/$(uname -m); Maison supports Apple Silicon macOS and supported Linux" ;;
esac

if [ ! -e .git ]; then
  git init --quiet
fi

export MAISON_OVERLAY_PATH="$overlay_path"
mise -C "$maison_home" run host:add -- "$host" --system "$system" --user "$username"
