alias ls='eza --icons=auto --git'
alias ll='eza -l --icons=auto --git'
alias la='eza -a --icons=auto --git'
alias lla='eza -la --icons=auto --git'
alias lt='eza --tree --icons=auto --git'
alias less='bat'
alias cat='bat'
alias oc='opencode'

# Site-specific directory shortcuts belong in a private overlay.
alias personal='cd ~/workspace/personal'

alias gst='git status'
alias gd='git diff'
alias ga='git add'
alias gc='git commit --verbose'
alias 'gc!'='git commit --verbose --amend'
alias gco='git checkout'
alias gdca='git diff --cached'
alias gbD='git branch --delete --force'
alias gbd='git branch --delete'

alias ..='up 1'
alias ...='up 2'
alias ....='up 3'
alias .....='up 4'
