[book]
title = "maison"
description = "Provide a reusable public configuration framework for supported macOS and Linux systems."
authors = []
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/RobertDeRose/maison"
edit-url-template = "https://github.com/RobertDeRose/maison/edit/main/docs/{path}"
additional-css = ["theme/cobalt.css"]
